/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 3dsource/pervyiprobnycosmonaut.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/pervyiprobnycosmonaut.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.root} />
          <skinnedMesh name="Backpack" geometry={nodes.Backpack.geometry} material={nodes.Backpack.material} skeleton={nodes.Backpack.skeleton} />
          <skinnedMesh name="Glove" geometry={nodes.Glove.geometry} material={nodes.Glove.material} skeleton={nodes.Glove.skeleton} />
          <skinnedMesh name="Helmet" geometry={nodes.Helmet.geometry} material={materials['Material.002']} skeleton={nodes.Helmet.skeleton} />
          <skinnedMesh name="Object004" geometry={nodes.Object004.geometry} material={nodes.Object004.material} skeleton={nodes.Object004.skeleton} />
          <skinnedMesh name="Shoes" geometry={nodes.Shoes.geometry} material={nodes.Shoes.material} skeleton={nodes.Shoes.skeleton} />
          <skinnedMesh name="Wearpack" geometry={nodes.Wearpack.geometry} material={materials['Material.001']} skeleton={nodes.Wearpack.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pervyiprobnycosmonaut.glb')
