name: Deploy

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SSH_USER }}
          server: ${{ secrets.SSH_SERVER }}
          password: ${{ secrets.SSH_PASSWORD }}
          local_path: './out/*'
          remote_path: '/domains/mustbefamily.com/public_html/test'
          delete_remote_files: true
          sftp_only: true
          sftpArgs: '-o ConnectTimeout=5'
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          directory: 'out'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifacts: 'out/release.zip'
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'latest'
